INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Тарировка топливной емкости до 8 тонн', '00-00000090' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Перевод на наш сервер (Стоимость годового обслуживания)', '00-00002022' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж взрывозащищенного ДУТ', '00-00003724' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж ДРТ / СЖ-ППО', 'ФР-00002228' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Премиальные - Карта монтажа (составление)', '00-00000253' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Работы по поверке приборов комплекса "Телемедик"', '00-00003185' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Тарировка топливной емкости до 2500 л', '00-00004053' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж беспроводного взрывозащищенного ДУТ', '00-00003899' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж видеорегистратора', '00-00003719' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Настройка программного обеспечения', '00-00001989' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж КТ З / КМВЗ', '00-00001665' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж датчика температуры', 'ФР-00002180' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж Тахографа', '00-00000504' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж датчика вращения', 'ФР-00002152' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Настройка ПО блока телемедицины', '00-00002982' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Сборка блока телемедицины', '00-00002979' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Создание презентаций ', '00-00001962' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Демонтаж топливного бака', '00-00000095' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж блокировки ДВС', '00-00000028' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Доставка', '00-00003786' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж датчика угла наклона', '00-00000383' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Диагностика Тахографа', '00-00000684' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Подключение доп. оборудования при установленной системе мониторинга', '00-00001918' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Восстановление работоспособности доп.оборудования', '00-00001909' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Восстановление работоспособности ДУТ', '00-00001908' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж индикаторной панели EGR LS', '00-00001883' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж беспроводного датчика угла наклона', '00-00003902' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж беспроводного датчика вращения', '00-00003901' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж беспроводного датчика температуры', '00-00003900' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж и настройка камеры', '00-00001058' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Восстановление подключения тахографа/датчиков', '00-00001969' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Выезд ведущего специалиста ТехПО', '00-00001958' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж датчика уровня топлива', 'ФР-00000061' , 'a');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Установка устройства ограничения скорости', '00-00004023' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж датчика расхода топлива', '00-00002620' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Тарировка топливного бака', '00-00001902' , 'd');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж БГР', '00-00000661' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж БИС', '00-00000660' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж тревожной кнопки', '00-00000397' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж считывателя CardReader / i-button', '00-00001435' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж КУСС / ТРК', '00-00000988' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж УСС / клапан', 'ФР-00002396' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж датчика скорости', '00-00000879' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Контрольный слив / заправка', 'ФР-00002188' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Подключение доп. оборудования при монтаже контроллера', '00-00000527' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж адаптера CAN-Log / NiCAN', 'ФР-00002214' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж адаптера VSSCAN', '00-00001299' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Подключение постоянного питания при монтаже контроллера', 'ФР-00002202' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Калибровка Тахографа (цифрового)', '00-00000507' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Восстановление работоспособности контроллера мониторинга', '00-00001907' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж датчика подъема кузова', '00-00001736' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж спидометра', '00-00001729' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Дополнительные работы', '00-00001668' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Дополнительные работы при монтаже/демонтаже тахографа', '00-00001078' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Прокладка кабеля от АКБ', '00-00000787' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Прокладка кабеля от ДС', '00-00000785' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Подключение к дополнительному оборудованию ТС+настройка', '00-00004025' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Установка прочих датчиков', '00-00004024' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж контроллера', 'ФР-00000070' , 'a');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж датчика контроля моточасов / оборотов', '00-00001133' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Демонтаж и/или вырезка защиты', '00-00000067' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Калибровка Тахографа (цифрового) при замене блока СКЗИ', '00-00002826' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж короба под тахограф', '00-00000647' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Подключение CAN шины при монтаже контроллера', 'ФР-00002205' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Считывание данных с тахографа / Карты', '00-00001878' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж беспроводного датчика уровня топлива', '00-00003903' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Демонтаж контроллера мониторинга', 'ФР-00002166' , 'e');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Демонтаж датчика', '00-00001934' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Активация модуля', '00-00000506' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж защитного короба (контроллеры)', '00-00001905' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Сопровождение клиента при создании личного кабинета ', '00-00003933' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Демонтаж тахографа / блока СКЗИ', '00-00001983' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Оформление карты предприятия', '00-00000931' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Оформление карты водителя', '00-00000884' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Оформление карты мастерской', '00-00001278' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Дополнительные работы по оформлению карты', '00-00001761' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Тарировка свыше 8 тонн за тонну', '00-00003898' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Простой специалиста при проведении работ', '00000003238' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Разблокировка карты', '00-00001747' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Метрологическая поверка тахографа', '00-00002067' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Демонтаж сторонней системы мониторинга', 'ФР-00000059' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж датчика TPMS', '00-00002069' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Осмотр техники на предмет установки системы мониторинга', 'ФР-00002393' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Активация Тахографа', '00-00000505' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Диагностика системы мониторинга', '00-00001910' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Срыв работ', '00-00003977' , 'z');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Монтаж 2х ДУТ', '4234234' , 'c');
INSERT INTO USLUGA (ID, NAME, CODE, PRIORITET) VALUES ( UUID(), 'Демонтаж 2х ДУТ', '2345435' , 'e');

