INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Тарировка топливной емкости до 8 тонн', '00-00000090' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Перевод на наш сервер (Стоимость годового обслуживания)', '00-00002022' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Монтаж взрывозащищенного ДУТ', '00-00003724' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Монтаж ДРТ / СЖ-ППО', 'ФР-00002228' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Премиальные - Карта монтажа (составление)', '00-00000253' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Работы по поверке приборов комплекса "Телемедик"', '00-00003185' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Тарировка топливной емкости до 2500 л', '00-00004053' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Монтаж беспроводного взрывозащищенного ДУТ', '00-00003899' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Монтаж видеорегистратора', '00-00003719' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Настройка программного обеспечения', '00-00001989' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Монтаж КТЗ / КМВЗ', '00-00001665' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Монтаж датчика температуры', 'ФР-00002180' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Монтаж Тахографа', '00-00000504' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Монтаж датчика вращения', 'ФР-00002152' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Настройка ПО блока телемедицины', '00-00002982' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Сборка блока телемедицины', '00-00002979' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Создание презентаций ', '00-00001962' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Демонтаж топливного бака', '00-00000095' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Монтаж блокировки ДВС', '00-00000028' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Доставка', '00-00003786' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Монтаж датчика угла наклона', '00-00000383' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Диагностика Тахографа', '00-00000684' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Подключение доп. оборудования при установленной системе мониторинга', '00-00001918' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Восстановление работоспособности доп.оборудования', '00-00001909' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Восстановление работоспособности ДУТ', '00-00001908' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Монтаж индикаторной панели EGR LS', '00-00001883' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Монтаж беспроводного датчика угла наклона', '00-00003902' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Монтаж беспроводного датчика вращения', '00-00003901' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Монтаж беспроводного датчика температуры', '00-00003900' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Монтаж и настройка камеры', '00-00001058' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Восстановление подключения тахографа/датчиков', '00-00001969' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Выезд ведущего специалиста ТехПО', '00-00001958' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Монтаж датчика уровня топлива', 'ФР-00000061' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Установка устройства ограничения скорости', '00-00004023' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Монтаж датчика расхода топлива', '00-00002620' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Тарировка топливного бака', '00-00001902' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Монтаж БГР', '00-00000661' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Монтаж БИС', '00-00000660' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Монтаж тревожной кнопки', '00-00000397' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Монтаж считывателя CardReader / i-button', '00-00001435' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Монтаж КУСС / ТРК', '00-00000988' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Монтаж УСС / клапан', 'ФР-00002396' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Монтаж датчика скорости', '00-00000879' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Контрольный слив / заправка', 'ФР-00002188' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Подключение доп. оборудования при монтаже контроллера', '00-00000527' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Монтаж адаптера CAN-Log / NiCAN', 'ФР-00002214' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Монтаж адаптера VSSCAN', '00-00001299' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Подключение постоянного питания при монтаже контроллера', 'ФР-00002202' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Калибровка Тахографа (цифрового)', '00-00000507' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Восстановление работоспособности контроллера мониторинга', '00-00001907' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Монтаж датчика подъема кузова', '00-00001736' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Монтаж спидометра', '00-00001729' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Дополнительные работы', '00-00001668' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Дополнительные работы при монтаже/демонтаже тахографа', '00-00001078' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Прокладка кабеля от АКБ', '00-00000787' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Прокладка кабеля от ДС', '00-00000785' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Подключение к дополнительному оборудованию ТС+настройка', '00-00004025' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Установка прочих датчиков', '00-00004024' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Монтаж контроллера', 'ФР-00000070' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Монтаж датчика контроля моточасов / оборотов', '00-00001133' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Демонтаж и/или вырезка защиты', '00-00000067' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Калибровка Тахографа (цифрового) при замене блока СКЗИ', '00-00002826' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Монтаж короба под тахограф', '00-00000647' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Подключение CAN шины при монтаже контроллера', 'ФР-00002205' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Считывание данных с тахографа / Карты', '00-00001878' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Монтаж беспроводного датчика уровня топлива', '00-00003903' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Демонтаж контроллера мониторинга', 'ФР-00002166' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Демонтаж датчика', '00-00001934' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Активация модуля', '00-00000506' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Монтаж защитного короба (контроллеры)', '00-00001905' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Сопровождение клиента при создании личного кабинета ', '00-00003933' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Демонтаж тахографа / блока СКЗИ', '00-00001983' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Оформление карты предприятия', '00-00000931' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Оформление карты водителя', '00-00000884' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Оформление карты мастерской', '00-00001278' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Дополнительные работы по оформлению карты', '00-00001761' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Тарировка свыше 8 тонн за тонну', '00-00003898' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Простой специалиста при проведении работ', '00000003238' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Разблокировка карты', '00-00001747' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Метрологическая поверка тахографа', '00-00002067' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Демонтаж сторонней системы мониторинга', 'ФР-00000059' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Монтаж датчика TPMS', '00-00002069' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Осмотр техники на предмет установки системы мониторинга', 'ФР-00002393' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Активация Тахографа', '00-00000505' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Диагностика системы мониторинга', '00-00001910' );
INSERT INTO USLUGA (ID, NAME, CODE) VALUES ( UUID(), 'Срыв работ', '00-00003977' );
