INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Активация модуля', '00-00000506' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Активация Тахографа', '00-00000505' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Восстановление подключения тахографа/датчиков', '00-00001969' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Восстановление работоспособности доп.оборудования', '00-00001909' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Восстановление работоспособности ДУТ', '00-00001908' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Восстановление работоспособности контроллера мониторинга', '00-00001907' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Демонтаж датчика', '00-00001934' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Демонтаж и/или вырезка защиты', '00-00000067' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Демонтаж контроллера мониторинга', 'ФР-00002166' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Демонтаж сторонней системы мониторинга', 'ФР-00000059' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Демонтаж тахографа / блока СКЗИ', '00-00001983' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Демонтаж топливного бака', '00-00000095' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Диагностика системы мониторинга', '00-00001910' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Диагностика Тахографа', '00-00000684' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Дополнительные работы', '00-00001668' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Калибровка Тахографа (цифрового)', '00-00000507' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Калибровка Тахографа (цифрового) при замене блока СКЗИ', '00-00002826' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Контрольный слив / заправка', 'ФР-00002188' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Монтаж адаптера CAN-Log / NiCAN', 'ФР-00002214' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Монтаж адаптера VSSCAN', '00-00001299' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Монтаж БГР', '00-00000661' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Монтаж беспроводного взрывозащищенного ДУТ', '00-00003899' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Монтаж беспроводного датчика вращения', '00-00003901' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Монтаж беспроводного датчика температуры', '00-00003900' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Монтаж беспроводного датчика угла наклона', '00-00003902' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Монтаж беспроводного датчика уровня топлива', '00-00003903' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Монтаж БИС', '00-00000660' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Монтаж блокировки ДВС', '00-00000028' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Монтаж взрывозащищенного ДУТ', '00-00003724' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Монтаж видеорегистратора', '00-00003719' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Монтаж датчика TPMS', '00-00002069' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Монтаж датчика вращения', 'ФР-00002152' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Монтаж датчика контроля моточасов / оборотов', '00-00001133' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Монтаж датчика подъема кузова', '00-00001736' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Монтаж датчика расхода топлива', '00-00002620' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Монтаж датчика скорости', '00-00000879' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Монтаж датчика температуры', 'ФР-00002180' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Монтаж датчика угла наклона', '00-00000383' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Монтаж датчика уровня топлива', 'ФР-00000061' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Монтаж ДРТ / СЖ-ППО', 'ФР-00002228' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Монтаж и настройка камеры', '00-00001058' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Монтаж индикаторной панели EGR LS', '00-00001883' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Монтаж контроллера', 'ФР-00000070' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Монтаж короба под тахограф', '00-00000647' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Монтаж КТЗ / КМВЗ', '00-00001665' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Монтаж КУСС / ТРК', '00-00000988' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Монтаж спидометра', '00-00001729' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Монтаж считывателя CardReader / i-button', '00-00001435' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Монтаж Тахографа', '00-00000504' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Монтаж тревожной кнопки', '00-00000397' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Монтаж УСС / клапан', 'ФР-00002396' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Осмотр техники на предмет установки системы мониторинга', 'ФР-00002393' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Подключение CAN шины при монтаже контроллера', 'ФР-00002205' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Подключение доп. оборудования при монтаже контроллера', '00-00000527' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Подключение доп. оборудования при установленной системе мониторинга', '00-00001918' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Подключение постоянного питания при монтаже контроллера', 'ФР-00002202' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Простой специалиста при проведении работ', '00000003238' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Срыв работ', '00-00003977' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Считывание данных с тахографа / Карты', '00-00001878' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Тарировка свыше 8 тонн за тонну', '00-00003898' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Тарировка топливного бака', '00-00001902' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Тарировка топливной емкости до 2500 л', '00-00004053' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Тарировка топливной емкости до 8 тонн', '00-00000090' , 'z');
INSERT INTO USLUGA (ID, TENANT_ATTRIBUTE, NAME, CODE, PRIORITET) VALUES ( UUID(), 'avtokonnekt','Установка устройства ограничения скорости', '00-00004023' , 'z');
